Repository AGH-CEAI/aegis_gym, pull requests merged in 2025-09, with the labels that each got.

#11 [Scene&Robot 1/5] Project files update
  .gitignore
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#17 Add Cartesian control in Reacher environment
  aegis_gym/envs/aegis_reacher.py
  aegis_gym/scene/robot_commander_interface.py
Labels: enhancement

#14 [Scene&Robot 4/5] Reacher & Pusher envs redesign
  aegis_gym/__init__.py
  aegis_gym/envs/__init__.py
  aegis_gym/envs/aegis_pusher.py
  aegis_gym/envs/aegis_reacher.py
  aegis_gym/envs/env_types.py
Labels: enhancement, env

#19 Implement Cartesian control for ROS robot commander
  .pre-commit-config.yaml
  CHANGELOG.md
  aegis_gym/__init__.py
  aegis_gym/ros/robot_commander_ros.py
Labels: enhancement
